### ISSUE TITLE
Cannot load credentials 

### ISSUE THREAD

**Issue by ntlzz93** [awslabs/aws-nodejs-sample#10]
I've created owner credentials on  ~/.aws/credentials on my mac but it throw an error

```
{ CredentialsError: Missing credentials in config
    at ClientRequest.<anonymous> (/Volumes/Data/Loint/aws-nodejs-sample/node_modules/aws-sdk/lib/http/node.js:83:34)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.emitTimeout (_http_client.js:679:10)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:188:7)
    at Socket._onTimeout (net.js:352:8)
    at ontimeout (timers.js:386:14)
  message: 'Missing credentials in config',
  code: 'CredentialsError',
  time: 2017-10-13T10:42:38.188Z,
  retryable: true,
  originalError: 
   { message: 'Could not load credentials from any providers',
     code: 'CredentialsError',
     time: 2017-10-13T10:42:38.188Z,
     retryable: true,
     originalError: 
      { message: 'Missing credentials in config',
        code: 'CredentialsError',
        time: 2017-10-13T10:42:38.178Z,
        retryable: true,
        originalError: [Object] } } }
```

please help

**Comment by alvarocardenasc** [comment]
could you solve it? I have the same problem

**Comment by i0na-k** [comment]
I had this problem aswell. Try the code that I have submitted as a PR -> https://github.com/aws-samples/aws-nodejs-sample/pull/12. 
Obtain the credentials from the AWS console then paste them into config.update.
